# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiControlPanel(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 377)
        self.slider_1 = QtWidgets.QSlider(Form)
        self.slider_1.setGeometry(QtCore.QRect(40, 80, 22, 160))
        self.slider_1.setOrientation(QtCore.Qt.Vertical)
        self.slider_1.setObjectName("slider_1")

        self.slider_2 = QtWidgets.QSlider(Form)
        self.slider_2.setGeometry(QtCore.QRect(100, 80, 22, 160))
        self.slider_2.setOrientation(QtCore.Qt.Vertical)
        self.slider_2.setObjectName("slider_2")

        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 250, 241, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.slider_3 = QtWidgets.QSlider(Form)
        self.slider_3.setGeometry(QtCore.QRect(160, 80, 22, 160))
        self.slider_3.setOrientation(QtCore.Qt.Vertical)
        self.slider_3.setObjectName("slider_3")

        self.slider_4 = QtWidgets.QSlider(Form)
        self.slider_4.setGeometry(QtCore.QRect(220, 80, 22, 160))
        self.slider_4.setOrientation(QtCore.Qt.Vertical)
        self.slider_4.setObjectName("slider_4")

        self.tittle_sliders = QtWidgets.QLabel(Form)
        self.tittle_sliders.setGeometry(QtCore.QRect(30, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tittle_sliders.setFont(font)
        self.tittle_sliders.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tittle_sliders.setObjectName("tittle_sliders")

        self.valve_1 = QtWidgets.QCheckBox(Form)
        self.valve_1.setGeometry(QtCore.QRect(30, 270, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.valve_1.setFont(font)
        self.valve_1.setObjectName("valve_1")

        self.valve_2 = QtWidgets.QCheckBox(Form)
        self.valve_2.setGeometry(QtCore.QRect(30, 310, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.valve_2.setFont(font)
        self.valve_2.setObjectName("valve_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tittle_sliders.setText(_translate("Form", "Positions of control rods"))
        self.valve_1.setText(_translate("Form", "Valve 1"))
        self.valve_2.setText(_translate("Form", "Valve 2"))
